name: tailf
description: A pure dart implementation of `tail -f` providing a stream of
  `Uint8Bytes`, `String`, or split by lines.
version: 1.1.1
repository: https://github.com/jtmcdole/tail_file
environment:
  sdk: ^3.5.0

executables:
  tailf:

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
