name: tail_file
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^4.0.0
  path: ^1.9.1
  test: ^1.24.0
