name: tailf 
description: A pure dart implementation of `tail -f` providing a stream of `Uint8Bytes`, `String`, or split by lines.
version: 1.0.2
repository: https://github.com/jtmcdole/tail_file
environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^4.0.0
  path: ^1.9.1
  test: ^1.24.0
